[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
hello-xenowits-methods = { path = "../methods" }
risc0-zkvm = { version = "0.18.0" }
serde = "1.0"
serde_json="1.0"
bincode = "1.3.3"
hex = { version = "0.4.3", features = [] }
log = "0.4.20"