[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello-xenowits-methods = { path = "../methods" }
risc0-zkvm = { version = "0.18.0" }
bincode = "1.3.3"